title: MultiNest example configuration file.

device: "cpu"
june_configuration_file: "./configs/tests.yaml"

results_path: "./results/multinest"

parameters_to_fit:
  model.infection_networks.networks.company.log_beta:
    prior:
      dist: Normal
      loc: 0.0
      scale: 1.0
  model.infection_networks.networks.school.log_beta:
    prior:
      dist: Normal
      loc: 0.0
      scale: 1.0
  model.infection_networks.networks.household.log_beta:
    prior:
      dist: Normal
      loc: 0.0
      scale: 1.0
  model.infection_networks.networks.care_home.log_beta:
    prior:
      dist: Normal
      loc: 0.0
      scale: 1.0
  model.infection_networks.networks.care_visit.log_beta:
    prior:
      dist: Normal
      loc: 0.0
      scale: 1.0
  model.infection_networks.networks.university.log_beta:
    prior:
      dist: Normal
      loc: 0.0
      scale: 1.0
  model.infection_networks.networks.leisure.log_beta:
    prior:
      dist: Normal
      loc: 0.0
      scale: 1.0

data:
  observed_data: "./results/june/results.csv"
  observable: 
    deaths_per_timestep:
      time_stamps: "all"
      error: 0.10


training:
  likelihood: Normal
