title: Normalizing flows example configuration file.

device: ["cpu"]

june_configuration_file: "./configs/june.yaml"

results_path: "./results/normflows"

parameters_to_fit:
  model.infection_networks.networks.company.log_beta:
    prior:
      dist: Normal
      loc: 0.0
      scale: 1.0
  model.infection_networks.networks.school.log_beta:
    prior:
      dist: Normal
      loc: 0.0
      scale: 1.0
  model.infection_networks.networks.household.log_beta:
    prior:
      dist: Normal
      loc: 0.0
      scale: 1.0


training:
  n_epochs: 250
  n_batch: 1
  loss:
    type: MSELoss
    reduction: mean
  optimizer:
    type: Adam
    lr: 0.001
      #betas: [0.95, 0.999]
    milestones: []
    gamma: 0.2
  flow:
    K: 8
    AutoregressiveRationalQuadraticSpline:
      num_input_channels: 3
      num_blocks: 2
      num_hidden_channels: 64
    LULinearPermute:
      num_channels: 3

data:
  observed_data: "./results/june/results.csv"
  observable: 
    cases_per_timestep:
      time_stamps: "all"
