title: UltraNest example configuration file.

device: "cpu"
june_configuration_file: "./configs/june.yaml"

results_path: "./results/ultranest"

parameters_to_fit:
  infection_networks.networks.company.log_beta:
    prior:
      dist: Normal
      loc: 0.1
      scale: 0.1
  infection_networks.networks.school.log_beta:
    prior:
      dist: Normal
      loc: 0.1
      scale: 0.1

data:
  observed_data: "./results/june/results.csv"
  observable: 
    cases_by_age_18:
      time_stamps: "all"
      error: 0.05
    cases_by_age_25:
      time_stamps: "all"
      error: 0.05
    cases_by_age_35:
      time_stamps: "all"
      error: 0.05
    cases_by_age_45:
      time_stamps: "all"
      error: 0.05
    cases_by_age_55:
      time_stamps: "all"
      error: 0.05
    cases_by_age_65:
      time_stamps: "all"
      error: 0.05
    cases_by_age_75:
      time_stamps: "all"
      error: 0.05
    cases_by_age_100:
      time_stamps: "all"
      error: 0.05

training:
  likelihood: Normal
